// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/platform/vm/vmrpc/vmrpc.proto

package vmrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostService_CallRuntimeTool_FullMethodName = "/vmrpc.HostService/CallRuntimeTool"
	HostService_CallRuntimeHTTP_FullMethodName = "/vmrpc.HostService/CallRuntimeHTTP"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is implemented by the Host and called by vmd.
// This allows guest-local runtime bridge requests to call back into the host.
type HostServiceClient interface {
	CallRuntimeTool(ctx context.Context, in *RuntimeToolRequest, opts ...grpc.CallOption) (*RuntimeToolResponse, error)
	CallRuntimeHTTP(ctx context.Context, in *RuntimeHTTPRequest, opts ...grpc.CallOption) (*RuntimeHTTPResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) CallRuntimeTool(ctx context.Context, in *RuntimeToolRequest, opts ...grpc.CallOption) (*RuntimeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeToolResponse)
	err := c.cc.Invoke(ctx, HostService_CallRuntimeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) CallRuntimeHTTP(ctx context.Context, in *RuntimeHTTPRequest, opts ...grpc.CallOption) (*RuntimeHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeHTTPResponse)
	err := c.cc.Invoke(ctx, HostService_CallRuntimeHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is implemented by the Host and called by vmd.
// This allows guest-local runtime bridge requests to call back into the host.
type HostServiceServer interface {
	CallRuntimeTool(context.Context, *RuntimeToolRequest) (*RuntimeToolResponse, error)
	CallRuntimeHTTP(context.Context, *RuntimeHTTPRequest) (*RuntimeHTTPResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) CallRuntimeTool(context.Context, *RuntimeToolRequest) (*RuntimeToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallRuntimeTool not implemented")
}
func (UnimplementedHostServiceServer) CallRuntimeHTTP(context.Context, *RuntimeHTTPRequest) (*RuntimeHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallRuntimeHTTP not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_CallRuntimeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CallRuntimeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CallRuntimeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CallRuntimeTool(ctx, req.(*RuntimeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_CallRuntimeHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CallRuntimeHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CallRuntimeHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CallRuntimeHTTP(ctx, req.(*RuntimeHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmrpc.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallRuntimeTool",
			Handler:    _HostService_CallRuntimeTool_Handler,
		},
		{
			MethodName: "CallRuntimeHTTP",
			Handler:    _HostService_CallRuntimeHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/platform/vm/vmrpc/vmrpc.proto",
}

const (
	VMService_Health_FullMethodName                   = "/vmrpc.VMService/Health"
	VMService_Exec_FullMethodName                     = "/vmrpc.VMService/Exec"
	VMService_ExecStream_FullMethodName               = "/vmrpc.VMService/ExecStream"
	VMService_CreateSandbox_FullMethodName            = "/vmrpc.VMService/CreateSandbox"
	VMService_DeleteSandbox_FullMethodName            = "/vmrpc.VMService/DeleteSandbox"
	VMService_SandboxExists_FullMethodName            = "/vmrpc.VMService/SandboxExists"
	VMService_MountSandbox_FullMethodName             = "/vmrpc.VMService/MountSandbox"
	VMService_UnmountSandbox_FullMethodName           = "/vmrpc.VMService/UnmountSandbox"
	VMService_GetSandboxFile_FullMethodName           = "/vmrpc.VMService/GetSandboxFile"
	VMService_StreamSandboxFile_FullMethodName        = "/vmrpc.VMService/StreamSandboxFile"
	VMService_UploadSandboxFile_FullMethodName        = "/vmrpc.VMService/UploadSandboxFile"
	VMService_WriteSandboxFile_FullMethodName         = "/vmrpc.VMService/WriteSandboxFile"
	VMService_DeleteSandboxFile_FullMethodName        = "/vmrpc.VMService/DeleteSandboxFile"
	VMService_SandboxFileExists_FullMethodName        = "/vmrpc.VMService/SandboxFileExists"
	VMService_SetupWorkspaces_FullMethodName          = "/vmrpc.VMService/SetupWorkspaces"
	VMService_GetSandboxState_FullMethodName          = "/vmrpc.VMService/GetSandboxState"
	VMService_ExportSandboxDiff_FullMethodName        = "/vmrpc.VMService/ExportSandboxDiff"
	VMService_DiscardSandboxAllChanges_FullMethodName = "/vmrpc.VMService/DiscardSandboxAllChanges"
	VMService_RunSandboxHousekeeper_FullMethodName    = "/vmrpc.VMService/RunSandboxHousekeeper"
	VMService_SetProxyEnv_FullMethodName              = "/vmrpc.VMService/SetProxyEnv"
	VMService_ResetSharedEnv_FullMethodName           = "/vmrpc.VMService/ResetSharedEnv"
	VMService_ExecutePython_FullMethodName            = "/vmrpc.VMService/ExecutePython"
	VMService_ExecutePythonStream_FullMethodName      = "/vmrpc.VMService/ExecutePythonStream"
	VMService_ProvisionAuthCredentials_FullMethodName = "/vmrpc.VMService/ProvisionAuthCredentials"
	VMService_SetRuntimeBridgeConfig_FullMethodName   = "/vmrpc.VMService/SetRuntimeBridgeConfig"
	VMService_SyncWorkspace_FullMethodName            = "/vmrpc.VMService/SyncWorkspace"
)

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMService is implemented by vmd and called by the Host.
// This is for sandbox operations inside the VM.
type VMServiceClient interface {
	// Health checks if the service is healthy.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Exec executes a command inside a sandbox.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// ExecStream executes a command and streams output.
	ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error)
	// Sandbox management
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error)
	SandboxExists(ctx context.Context, in *SandboxExistsRequest, opts ...grpc.CallOption) (*SandboxExistsResponse, error)
	MountSandbox(ctx context.Context, in *MountSandboxRequest, opts ...grpc.CallOption) (*MountSandboxResponse, error)
	UnmountSandbox(ctx context.Context, in *UnmountSandboxRequest, opts ...grpc.CallOption) (*UnmountSandboxResponse, error)
	// File operations
	GetSandboxFile(ctx context.Context, in *GetSandboxFileRequest, opts ...grpc.CallOption) (*GetSandboxFileResponse, error)
	StreamSandboxFile(ctx context.Context, in *StreamSandboxFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSandboxFileChunk], error)
	UploadSandboxFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadSandboxFileChunk, UploadSandboxFileResponse], error)
	WriteSandboxFile(ctx context.Context, in *WriteSandboxFileRequest, opts ...grpc.CallOption) (*WriteSandboxFileResponse, error)
	DeleteSandboxFile(ctx context.Context, in *DeleteSandboxFileRequest, opts ...grpc.CallOption) (*DeleteSandboxFileResponse, error)
	SandboxFileExists(ctx context.Context, in *SandboxFileExistsRequest, opts ...grpc.CallOption) (*SandboxFileExistsResponse, error)
	// Sandbox state operations
	SetupWorkspaces(ctx context.Context, in *SetupWorkspacesRequest, opts ...grpc.CallOption) (*SetupWorkspacesResponse, error)
	GetSandboxState(ctx context.Context, in *GetSandboxStateRequest, opts ...grpc.CallOption) (*GetSandboxStateResponse, error)
	ExportSandboxDiff(ctx context.Context, in *ExportSandboxDiffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportSandboxDiffResponse], error)
	DiscardSandboxAllChanges(ctx context.Context, in *DiscardSandboxAllChangesRequest, opts ...grpc.CallOption) (*DiscardSandboxAllChangesResponse, error)
	RunSandboxHousekeeper(ctx context.Context, in *RunSandboxHousekeeperRequest, opts ...grpc.CallOption) (*RunSandboxHousekeeperResponse, error)
	// Environment
	SetProxyEnv(ctx context.Context, in *SetProxyEnvRequest, opts ...grpc.CallOption) (*SetProxyEnvResponse, error)
	ResetSharedEnv(ctx context.Context, in *ResetSharedEnvRequest, opts ...grpc.CallOption) (*ResetSharedEnvResponse, error)
	// Python execution
	ExecutePython(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (*ExecutePythonResponse, error)
	ExecutePythonStream(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error)
	// Remote VM auth provisioning
	ProvisionAuthCredentials(ctx context.Context, in *ProvisionAuthCredentialsRequest, opts ...grpc.CallOption) (*ProvisionAuthCredentialsResponse, error)
	// Runtime bridge configuration for guest-local proxying.
	SetRuntimeBridgeConfig(ctx context.Context, in *SetRuntimeBridgeConfigRequest, opts ...grpc.CallOption) (*SetRuntimeBridgeConfigResponse, error)
	// SyncWorkspace streams a tar archive of workspace files to the remote VM.
	// Used in remote mode to upload initial workspace content.
	SyncWorkspace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncWorkspaceChunk, SyncWorkspaceResponse], error)
}

type vMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMServiceClient(cc grpc.ClientConnInterface) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, VMService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, VMService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[0], VMService_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExecStreamClient = grpc.ServerStreamingClient[ExecOutput]

func (c *vMServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, VMService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxResponse)
	err := c.cc.Invoke(ctx, VMService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SandboxExists(ctx context.Context, in *SandboxExistsRequest, opts ...grpc.CallOption) (*SandboxExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxExistsResponse)
	err := c.cc.Invoke(ctx, VMService_SandboxExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) MountSandbox(ctx context.Context, in *MountSandboxRequest, opts ...grpc.CallOption) (*MountSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountSandboxResponse)
	err := c.cc.Invoke(ctx, VMService_MountSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) UnmountSandbox(ctx context.Context, in *UnmountSandboxRequest, opts ...grpc.CallOption) (*UnmountSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmountSandboxResponse)
	err := c.cc.Invoke(ctx, VMService_UnmountSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetSandboxFile(ctx context.Context, in *GetSandboxFileRequest, opts ...grpc.CallOption) (*GetSandboxFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxFileResponse)
	err := c.cc.Invoke(ctx, VMService_GetSandboxFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) StreamSandboxFile(ctx context.Context, in *StreamSandboxFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSandboxFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[1], VMService_StreamSandboxFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSandboxFileRequest, StreamSandboxFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_StreamSandboxFileClient = grpc.ServerStreamingClient[StreamSandboxFileChunk]

func (c *vMServiceClient) UploadSandboxFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadSandboxFileChunk, UploadSandboxFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[2], VMService_UploadSandboxFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadSandboxFileChunk, UploadSandboxFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_UploadSandboxFileClient = grpc.ClientStreamingClient[UploadSandboxFileChunk, UploadSandboxFileResponse]

func (c *vMServiceClient) WriteSandboxFile(ctx context.Context, in *WriteSandboxFileRequest, opts ...grpc.CallOption) (*WriteSandboxFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteSandboxFileResponse)
	err := c.cc.Invoke(ctx, VMService_WriteSandboxFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) DeleteSandboxFile(ctx context.Context, in *DeleteSandboxFileRequest, opts ...grpc.CallOption) (*DeleteSandboxFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxFileResponse)
	err := c.cc.Invoke(ctx, VMService_DeleteSandboxFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SandboxFileExists(ctx context.Context, in *SandboxFileExistsRequest, opts ...grpc.CallOption) (*SandboxFileExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxFileExistsResponse)
	err := c.cc.Invoke(ctx, VMService_SandboxFileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SetupWorkspaces(ctx context.Context, in *SetupWorkspacesRequest, opts ...grpc.CallOption) (*SetupWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupWorkspacesResponse)
	err := c.cc.Invoke(ctx, VMService_SetupWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetSandboxState(ctx context.Context, in *GetSandboxStateRequest, opts ...grpc.CallOption) (*GetSandboxStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxStateResponse)
	err := c.cc.Invoke(ctx, VMService_GetSandboxState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ExportSandboxDiff(ctx context.Context, in *ExportSandboxDiffRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportSandboxDiffResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[3], VMService_ExportSandboxDiff_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportSandboxDiffRequest, ExportSandboxDiffResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExportSandboxDiffClient = grpc.ServerStreamingClient[ExportSandboxDiffResponse]

func (c *vMServiceClient) DiscardSandboxAllChanges(ctx context.Context, in *DiscardSandboxAllChangesRequest, opts ...grpc.CallOption) (*DiscardSandboxAllChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardSandboxAllChangesResponse)
	err := c.cc.Invoke(ctx, VMService_DiscardSandboxAllChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) RunSandboxHousekeeper(ctx context.Context, in *RunSandboxHousekeeperRequest, opts ...grpc.CallOption) (*RunSandboxHousekeeperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSandboxHousekeeperResponse)
	err := c.cc.Invoke(ctx, VMService_RunSandboxHousekeeper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SetProxyEnv(ctx context.Context, in *SetProxyEnvRequest, opts ...grpc.CallOption) (*SetProxyEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProxyEnvResponse)
	err := c.cc.Invoke(ctx, VMService_SetProxyEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ResetSharedEnv(ctx context.Context, in *ResetSharedEnvRequest, opts ...grpc.CallOption) (*ResetSharedEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetSharedEnvResponse)
	err := c.cc.Invoke(ctx, VMService_ResetSharedEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ExecutePython(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (*ExecutePythonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePythonResponse)
	err := c.cc.Invoke(ctx, VMService_ExecutePython_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ExecutePythonStream(ctx context.Context, in *ExecutePythonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[4], VMService_ExecutePythonStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutePythonRequest, ExecOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExecutePythonStreamClient = grpc.ServerStreamingClient[ExecOutput]

func (c *vMServiceClient) ProvisionAuthCredentials(ctx context.Context, in *ProvisionAuthCredentialsRequest, opts ...grpc.CallOption) (*ProvisionAuthCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionAuthCredentialsResponse)
	err := c.cc.Invoke(ctx, VMService_ProvisionAuthCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SetRuntimeBridgeConfig(ctx context.Context, in *SetRuntimeBridgeConfigRequest, opts ...grpc.CallOption) (*SetRuntimeBridgeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRuntimeBridgeConfigResponse)
	err := c.cc.Invoke(ctx, VMService_SetRuntimeBridgeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SyncWorkspace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncWorkspaceChunk, SyncWorkspaceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[5], VMService_SyncWorkspace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncWorkspaceChunk, SyncWorkspaceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_SyncWorkspaceClient = grpc.ClientStreamingClient[SyncWorkspaceChunk, SyncWorkspaceResponse]

// VMServiceServer is the server API for VMService service.
// All implementations must embed UnimplementedVMServiceServer
// for forward compatibility.
//
// VMService is implemented by vmd and called by the Host.
// This is for sandbox operations inside the VM.
type VMServiceServer interface {
	// Health checks if the service is healthy.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Exec executes a command inside a sandbox.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// ExecStream executes a command and streams output.
	ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutput]) error
	// Sandbox management
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error)
	SandboxExists(context.Context, *SandboxExistsRequest) (*SandboxExistsResponse, error)
	MountSandbox(context.Context, *MountSandboxRequest) (*MountSandboxResponse, error)
	UnmountSandbox(context.Context, *UnmountSandboxRequest) (*UnmountSandboxResponse, error)
	// File operations
	GetSandboxFile(context.Context, *GetSandboxFileRequest) (*GetSandboxFileResponse, error)
	StreamSandboxFile(*StreamSandboxFileRequest, grpc.ServerStreamingServer[StreamSandboxFileChunk]) error
	UploadSandboxFile(grpc.ClientStreamingServer[UploadSandboxFileChunk, UploadSandboxFileResponse]) error
	WriteSandboxFile(context.Context, *WriteSandboxFileRequest) (*WriteSandboxFileResponse, error)
	DeleteSandboxFile(context.Context, *DeleteSandboxFileRequest) (*DeleteSandboxFileResponse, error)
	SandboxFileExists(context.Context, *SandboxFileExistsRequest) (*SandboxFileExistsResponse, error)
	// Sandbox state operations
	SetupWorkspaces(context.Context, *SetupWorkspacesRequest) (*SetupWorkspacesResponse, error)
	GetSandboxState(context.Context, *GetSandboxStateRequest) (*GetSandboxStateResponse, error)
	ExportSandboxDiff(*ExportSandboxDiffRequest, grpc.ServerStreamingServer[ExportSandboxDiffResponse]) error
	DiscardSandboxAllChanges(context.Context, *DiscardSandboxAllChangesRequest) (*DiscardSandboxAllChangesResponse, error)
	RunSandboxHousekeeper(context.Context, *RunSandboxHousekeeperRequest) (*RunSandboxHousekeeperResponse, error)
	// Environment
	SetProxyEnv(context.Context, *SetProxyEnvRequest) (*SetProxyEnvResponse, error)
	ResetSharedEnv(context.Context, *ResetSharedEnvRequest) (*ResetSharedEnvResponse, error)
	// Python execution
	ExecutePython(context.Context, *ExecutePythonRequest) (*ExecutePythonResponse, error)
	ExecutePythonStream(*ExecutePythonRequest, grpc.ServerStreamingServer[ExecOutput]) error
	// Remote VM auth provisioning
	ProvisionAuthCredentials(context.Context, *ProvisionAuthCredentialsRequest) (*ProvisionAuthCredentialsResponse, error)
	// Runtime bridge configuration for guest-local proxying.
	SetRuntimeBridgeConfig(context.Context, *SetRuntimeBridgeConfigRequest) (*SetRuntimeBridgeConfigResponse, error)
	// SyncWorkspace streams a tar archive of workspace files to the remote VM.
	// Used in remote mode to upload initial workspace content.
	SyncWorkspace(grpc.ClientStreamingServer[SyncWorkspaceChunk, SyncWorkspaceResponse]) error
	mustEmbedUnimplementedVMServiceServer()
}

// UnimplementedVMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMServiceServer struct{}

func (UnimplementedVMServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVMServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedVMServiceServer) ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedVMServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedVMServiceServer) DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedVMServiceServer) SandboxExists(context.Context, *SandboxExistsRequest) (*SandboxExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxExists not implemented")
}
func (UnimplementedVMServiceServer) MountSandbox(context.Context, *MountSandboxRequest) (*MountSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MountSandbox not implemented")
}
func (UnimplementedVMServiceServer) UnmountSandbox(context.Context, *UnmountSandboxRequest) (*UnmountSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmountSandbox not implemented")
}
func (UnimplementedVMServiceServer) GetSandboxFile(context.Context, *GetSandboxFileRequest) (*GetSandboxFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxFile not implemented")
}
func (UnimplementedVMServiceServer) StreamSandboxFile(*StreamSandboxFileRequest, grpc.ServerStreamingServer[StreamSandboxFileChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamSandboxFile not implemented")
}
func (UnimplementedVMServiceServer) UploadSandboxFile(grpc.ClientStreamingServer[UploadSandboxFileChunk, UploadSandboxFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadSandboxFile not implemented")
}
func (UnimplementedVMServiceServer) WriteSandboxFile(context.Context, *WriteSandboxFileRequest) (*WriteSandboxFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteSandboxFile not implemented")
}
func (UnimplementedVMServiceServer) DeleteSandboxFile(context.Context, *DeleteSandboxFileRequest) (*DeleteSandboxFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandboxFile not implemented")
}
func (UnimplementedVMServiceServer) SandboxFileExists(context.Context, *SandboxFileExistsRequest) (*SandboxFileExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxFileExists not implemented")
}
func (UnimplementedVMServiceServer) SetupWorkspaces(context.Context, *SetupWorkspacesRequest) (*SetupWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupWorkspaces not implemented")
}
func (UnimplementedVMServiceServer) GetSandboxState(context.Context, *GetSandboxStateRequest) (*GetSandboxStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxState not implemented")
}
func (UnimplementedVMServiceServer) ExportSandboxDiff(*ExportSandboxDiffRequest, grpc.ServerStreamingServer[ExportSandboxDiffResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportSandboxDiff not implemented")
}
func (UnimplementedVMServiceServer) DiscardSandboxAllChanges(context.Context, *DiscardSandboxAllChangesRequest) (*DiscardSandboxAllChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardSandboxAllChanges not implemented")
}
func (UnimplementedVMServiceServer) RunSandboxHousekeeper(context.Context, *RunSandboxHousekeeperRequest) (*RunSandboxHousekeeperResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSandboxHousekeeper not implemented")
}
func (UnimplementedVMServiceServer) SetProxyEnv(context.Context, *SetProxyEnvRequest) (*SetProxyEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProxyEnv not implemented")
}
func (UnimplementedVMServiceServer) ResetSharedEnv(context.Context, *ResetSharedEnvRequest) (*ResetSharedEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetSharedEnv not implemented")
}
func (UnimplementedVMServiceServer) ExecutePython(context.Context, *ExecutePythonRequest) (*ExecutePythonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePython not implemented")
}
func (UnimplementedVMServiceServer) ExecutePythonStream(*ExecutePythonRequest, grpc.ServerStreamingServer[ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecutePythonStream not implemented")
}
func (UnimplementedVMServiceServer) ProvisionAuthCredentials(context.Context, *ProvisionAuthCredentialsRequest) (*ProvisionAuthCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionAuthCredentials not implemented")
}
func (UnimplementedVMServiceServer) SetRuntimeBridgeConfig(context.Context, *SetRuntimeBridgeConfigRequest) (*SetRuntimeBridgeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRuntimeBridgeConfig not implemented")
}
func (UnimplementedVMServiceServer) SyncWorkspace(grpc.ClientStreamingServer[SyncWorkspaceChunk, SyncWorkspaceResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncWorkspace not implemented")
}
func (UnimplementedVMServiceServer) mustEmbedUnimplementedVMServiceServer() {}
func (UnimplementedVMServiceServer) testEmbeddedByValue()                   {}

// UnsafeVMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMServiceServer will
// result in compilation errors.
type UnsafeVMServiceServer interface {
	mustEmbedUnimplementedVMServiceServer()
}

func RegisterVMServiceServer(s grpc.ServiceRegistrar, srv VMServiceServer) {
	// If the following call panics, it indicates UnimplementedVMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMService_ServiceDesc, srv)
}

func _VMService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).ExecStream(m, &grpc.GenericServerStream[ExecRequest, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExecStreamServer = grpc.ServerStreamingServer[ExecOutput]

func _VMService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SandboxExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SandboxExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SandboxExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SandboxExists(ctx, req.(*SandboxExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_MountSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).MountSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_MountSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).MountSandbox(ctx, req.(*MountSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_UnmountSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).UnmountSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_UnmountSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).UnmountSandbox(ctx, req.(*UnmountSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetSandboxFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetSandboxFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetSandboxFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetSandboxFile(ctx, req.(*GetSandboxFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_StreamSandboxFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSandboxFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).StreamSandboxFile(m, &grpc.GenericServerStream[StreamSandboxFileRequest, StreamSandboxFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_StreamSandboxFileServer = grpc.ServerStreamingServer[StreamSandboxFileChunk]

func _VMService_UploadSandboxFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VMServiceServer).UploadSandboxFile(&grpc.GenericServerStream[UploadSandboxFileChunk, UploadSandboxFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_UploadSandboxFileServer = grpc.ClientStreamingServer[UploadSandboxFileChunk, UploadSandboxFileResponse]

func _VMService_WriteSandboxFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteSandboxFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).WriteSandboxFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_WriteSandboxFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).WriteSandboxFile(ctx, req.(*WriteSandboxFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_DeleteSandboxFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).DeleteSandboxFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_DeleteSandboxFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).DeleteSandboxFile(ctx, req.(*DeleteSandboxFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SandboxFileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxFileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SandboxFileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SandboxFileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SandboxFileExists(ctx, req.(*SandboxFileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SetupWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SetupWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SetupWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SetupWorkspaces(ctx, req.(*SetupWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetSandboxState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetSandboxState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetSandboxState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetSandboxState(ctx, req.(*GetSandboxStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ExportSandboxDiff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportSandboxDiffRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).ExportSandboxDiff(m, &grpc.GenericServerStream[ExportSandboxDiffRequest, ExportSandboxDiffResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExportSandboxDiffServer = grpc.ServerStreamingServer[ExportSandboxDiffResponse]

func _VMService_DiscardSandboxAllChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardSandboxAllChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).DiscardSandboxAllChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_DiscardSandboxAllChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).DiscardSandboxAllChanges(ctx, req.(*DiscardSandboxAllChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_RunSandboxHousekeeper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSandboxHousekeeperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).RunSandboxHousekeeper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_RunSandboxHousekeeper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).RunSandboxHousekeeper(ctx, req.(*RunSandboxHousekeeperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SetProxyEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProxyEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SetProxyEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SetProxyEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SetProxyEnv(ctx, req.(*SetProxyEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ResetSharedEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSharedEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ResetSharedEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ResetSharedEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ResetSharedEnv(ctx, req.(*ResetSharedEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ExecutePython_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePythonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ExecutePython(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ExecutePython_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ExecutePython(ctx, req.(*ExecutePythonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ExecutePythonStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutePythonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).ExecutePythonStream(m, &grpc.GenericServerStream[ExecutePythonRequest, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_ExecutePythonStreamServer = grpc.ServerStreamingServer[ExecOutput]

func _VMService_ProvisionAuthCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionAuthCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ProvisionAuthCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ProvisionAuthCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ProvisionAuthCredentials(ctx, req.(*ProvisionAuthCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SetRuntimeBridgeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRuntimeBridgeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SetRuntimeBridgeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SetRuntimeBridgeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SetRuntimeBridgeConfig(ctx, req.(*SetRuntimeBridgeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SyncWorkspace_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VMServiceServer).SyncWorkspace(&grpc.GenericServerStream[SyncWorkspaceChunk, SyncWorkspaceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_SyncWorkspaceServer = grpc.ClientStreamingServer[SyncWorkspaceChunk, SyncWorkspaceResponse]

// VMService_ServiceDesc is the grpc.ServiceDesc for VMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmrpc.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VMService_Health_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _VMService_Exec_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _VMService_CreateSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _VMService_DeleteSandbox_Handler,
		},
		{
			MethodName: "SandboxExists",
			Handler:    _VMService_SandboxExists_Handler,
		},
		{
			MethodName: "MountSandbox",
			Handler:    _VMService_MountSandbox_Handler,
		},
		{
			MethodName: "UnmountSandbox",
			Handler:    _VMService_UnmountSandbox_Handler,
		},
		{
			MethodName: "GetSandboxFile",
			Handler:    _VMService_GetSandboxFile_Handler,
		},
		{
			MethodName: "WriteSandboxFile",
			Handler:    _VMService_WriteSandboxFile_Handler,
		},
		{
			MethodName: "DeleteSandboxFile",
			Handler:    _VMService_DeleteSandboxFile_Handler,
		},
		{
			MethodName: "SandboxFileExists",
			Handler:    _VMService_SandboxFileExists_Handler,
		},
		{
			MethodName: "SetupWorkspaces",
			Handler:    _VMService_SetupWorkspaces_Handler,
		},
		{
			MethodName: "GetSandboxState",
			Handler:    _VMService_GetSandboxState_Handler,
		},
		{
			MethodName: "DiscardSandboxAllChanges",
			Handler:    _VMService_DiscardSandboxAllChanges_Handler,
		},
		{
			MethodName: "RunSandboxHousekeeper",
			Handler:    _VMService_RunSandboxHousekeeper_Handler,
		},
		{
			MethodName: "SetProxyEnv",
			Handler:    _VMService_SetProxyEnv_Handler,
		},
		{
			MethodName: "ResetSharedEnv",
			Handler:    _VMService_ResetSharedEnv_Handler,
		},
		{
			MethodName: "ExecutePython",
			Handler:    _VMService_ExecutePython_Handler,
		},
		{
			MethodName: "ProvisionAuthCredentials",
			Handler:    _VMService_ProvisionAuthCredentials_Handler,
		},
		{
			MethodName: "SetRuntimeBridgeConfig",
			Handler:    _VMService_SetRuntimeBridgeConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _VMService_ExecStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSandboxFile",
			Handler:       _VMService_StreamSandboxFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadSandboxFile",
			Handler:       _VMService_UploadSandboxFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportSandboxDiff",
			Handler:       _VMService_ExportSandboxDiff_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecutePythonStream",
			Handler:       _VMService_ExecutePythonStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncWorkspace",
			Handler:       _VMService_SyncWorkspace_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/platform/vm/vmrpc/vmrpc.proto",
}

const (
	TelemetryService_ExportOTLP_FullMethodName = "/vmrpc.TelemetryService/ExportOTLP"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelemetryService is implemented by the Host and called by vmd.
// It allows the Guest to export OTLP payloads over the existing vmrpc channel.
type TelemetryServiceClient interface {
	ExportOTLP(ctx context.Context, in *OtlpEnvelope, opts ...grpc.CallOption) (*ExportAck, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) ExportOTLP(ctx context.Context, in *OtlpEnvelope, opts ...grpc.CallOption) (*ExportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportAck)
	err := c.cc.Invoke(ctx, TelemetryService_ExportOTLP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
//
// TelemetryService is implemented by the Host and called by vmd.
// It allows the Guest to export OTLP payloads over the existing vmrpc channel.
type TelemetryServiceServer interface {
	ExportOTLP(context.Context, *OtlpEnvelope) (*ExportAck, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) ExportOTLP(context.Context, *OtlpEnvelope) (*ExportAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportOTLP not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_ExportOTLP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtlpEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ExportOTLP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ExportOTLP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ExportOTLP(ctx, req.(*OtlpEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmrpc.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportOTLP",
			Handler:    _TelemetryService_ExportOTLP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/platform/vm/vmrpc/vmrpc.proto",
}
